# Generated by Django 5.1.7 on 2025-03-07 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='athlete',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
