# Generated by Django 5.1.7 on 2025-03-10 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0002_athlete_first_name_athlete_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='location',
            field=models.TextField(blank=True, null=True),
        ),
    ]
