# Generated by Django 5.1.7 on 2025-03-10 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0003_athlete_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
