# Generated by Django 5.1.7 on 2025-03-10 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0006_recruiter_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='athletes/'),
        ),
        migrations.AddField(
            model_name='recruiter',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='athletes/'),
        ),
    ]
