# Generated by Django 5.1.7 on 2025-03-10 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0007_athlete_profile_picture_recruiter_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruiter',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='recruiters/'),
        ),
    ]
