# Generated by Django 5.1.7 on 2025-03-12 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0009_athlete_birth_date_recruiter_birth_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='athlete',
            name='birth_date',
        ),
    ]
