# Generated by Django 5.1.7 on 2025-03-12 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0010_remove_athlete_birth_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruiter',
            name='birth_date',
        ),
    ]
