# Generated by Django 5.1.7 on 2025-03-13 23:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0014_athlete_email_athlete_facebook_athlete_instagram_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SportPortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('sport', models.CharField(max_length=100)),
                ('position', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('portfolio_image', models.ImageField(blank=True, null=True, upload_to='portfolio_images/')),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sport_portfolios', to='myproject.athlete')),
            ],
        ),
        migrations.CreateModel(
            name='SportPortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('about', 'About Me'), ('stats', 'Stats'), ('media', 'Media Gallery'), ('metrics', 'Performance Metrics'), ('contact', 'Contact'), ('text', 'Text'), ('image', 'Image'), ('video', 'Video')], max_length=20)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('data', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='portfolio_items/')),
                ('order', models.IntegerField(default=0)),
                ('sport_portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='myproject.sportportfolio')),
            ],
        ),
    ]
