# Generated by Django 5.1.7 on 2025-03-14 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0015_sportportfolio_sportportfolioitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='sportportfolio',
            name='team',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sportportfolio',
            name='sport',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sportportfolio',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
