# Generated by Django 5.1.7 on 2025-03-17 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0016_sportportfolio_team_alter_sportportfolio_sport_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportportfolioitem',
            name='category',
            field=models.CharField(choices=[('stats', 'Stats'), ('metrics', 'Performance Metrics'), ('image', 'Image Gallery'), ('video', 'Video')], max_length=20),
        ),
    ]
